title: Aeshus' Website
description: >-
  Some
  Words
  Here
baseurl: ""
url: ""

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:name


asciidoctor:
  template_dir: _templates

nav:
  - title: Aeshus' Home
    url: /
  - title: Articles
    url: /articles
  - title: Projects
    url: /projects
  - title: About
    url: /about
  - title: Colophon
    url: /colophon
