title: Aeshus' Website
description: >-
  Some
  Words
  Here
baseurl: ""
url: ""

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:name


asciidoctor:
  template_dir: _templates

