# Base Config

url: "https://aeshus.com"	# Base hostname & protocol for your site, e.g. http://example.com
baseurl: "/"			# Subpath of your site, e.g. /blog
title: "aeshus.com"             # Name of your site, e.g. ACME Corp.
description: "Programming blog" # Default description of your site, eg. "Programming blog"

author:
  name: Aeshus
  email: hi@aeshus.com

safe: false # ???

# Jekyll Feed

feed:
  collections:                  # Collections ti generate atom feed for
    articles:
      path: "/articles/feed.xml"

# Jekyll Asciidoctor

asciidoctor:
  backend: html5s
#  template_dir: _templates     # Directory for custom asciidoc html templates
  attributes:
    - page-layout=default      # Default layout for .adoc pages
    - iconsdir=/assets/icons   # Directory for icons
    - icons=image              # Use icons instead of fonts
    - icontype=svg             # Use SVGs for icons

# Jekyll Collections

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:name
