# Website Parameters

baseURL = 'https://aeshus.com/'
languageCode = 'en-us'
title = "Aeshus"
theme = "ouroboros"


[markup.asciidocExt]
  preserveTOC = true

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[menus]
[[menus.main]]
	name = "Aeshus"
	pageRef = "/"
	weight = 10
[[menus.main]]
	name = "Articles"
	pageRef = "/articles"
	weight = 20
[[menus.main]]
	name = "Projects"
	pageRef = "/projects"
	weight = 20
[[menus.main]]
	name = "About"
	pageRef = "/about"
	weight = 30
